---
- name: Create mariadb backup dir
  file:
    path: "{{ VAR_MARIADB_BACKUP_DIR }}"
    recurse: yes
    state: directory

- name: Copy backup template to /etc/cron.daily
  template:
    src: backup-mariadb.j2
    dest: /etc/cron.daily/backup-mariadb
    owner: root
    group: root
    mode: 0755

